server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://42.194.242.24:3306/guli_product?useUnicode=true&characterEncoding=utf-8&use
    username: root
    password: 123456
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
  application:
    name: mall-product

